# This is the main configuration block for your build.
[build]
  # The command Netlify runs to build your entire project.
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"
  
  # The directory where your serverless functions are located.
  functions = "backend/functions/"
  
  # The directory that contains your built frontend to be deployed.
  publish = "frontend/dist/"

# --- REDIRECTS ---
# The order of these rules is critical.

# This rule MUST be first. It directs all API calls to our serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# This rule MUST be last. It's the catch-all that sends every other request
# to your React app, allowing React Router to handle the page changes.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200