[build]
  # This tells Netlify where your serverless functions are located.
  functions = "backend/functions/"
  # This tells Netlify where your built frontend is.
  publish = "frontend/dist/"

# This is the command Netlify will run to build your project.
# It installs dependencies for both backend and frontend, then builds the frontend.
[build.command]
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"

# --- REDIRECT RULES ---
# The order here is CRITICAL.

# 1. API Rule (Most Specific)
# This rule MUST come first. It directs all API calls to our serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# 2. Frontend Rule (Catch-All)
# This rule comes last. It handles all other requests by sending them to the React app.
# This is what makes frontend routing (React Router) work.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200