[build]
  # We no longer need to install root dependencies, just frontend ones.
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "backend/functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200