[build]
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "backend/functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
