[build]
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "backend/functions/"

# This is the new rule. It's the most important one for React apps.
[[redirects]]
  # The path to redirect from
  from = "/*" 
  # The path to redirect to
  to = "/index.html"
  # The HTTP status code
  status = 200 