[build]
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "backend/functions/" # This path is still correct

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat" # This path is also still correct
  status = 200